#!/bin/bash

#sudo apt-get install python-lxml

curdir=`pwd`

if [ $# -eq 1 ] && [ $1 = 'c' ]
then
	cl="c"
else
	cl="i"
fi

ncam=/usr/lib/pymodules/python2.7/gladevcp
if [ -L $ncam/ncam.py ]
then
	if [ $cl = 'c' ]
	then
		sudo rm $ncam/ncam.py
	fi
else
	if [ $cl = 'i' ]	
	then
		sudo ln $curdir/ncam.py $ncam/ -s
	fi
fi

sudo python $curdir/ncam_setup2.py $1
