#!/bin/bash

curdir=`pwd`
	
newpath=/usr/share/pyshared/gladevcp
if [ -L $newpath/linuxcnc-features ]
then
	sudo rm $newpath/linuxcnc-features
fi

glade=/usr/share/pyshared/gladevcp/features.glade
if [ -L $glade ]
then
	sudo rm $glade
fi

features=/usr/share/pyshared/gladevcp/features.py
if [ -L $features ]
then
	sudo rm $features
fi

glade=/usr/lib/pymodules/python2.7/gladevcp/features.glade
if [ -L $glade ]
then
	sudo rm $glade
fi

features=/usr/lib/pymodules/python2.7/gladevcp/features.py
if [ -L $features ]
then
	sudo rm $features
fi

sudo python $curdir/uninstall_features.py c
